services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/alexandrefoley/qbittorrent
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
      - WEBUI_USERNAME=starruser
      - WEBUI_PASSWORD=use-a-real-password
      - LIBTORRENT=v2
    volumes:
      - config:/config
      - media:/media

volumes:
  config:
    driver: local
  media:
    driver: local