services:
  qbittorrent:
    container_name: qbittorrent
    image: qbittest
    ports:
      - "8080:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp
      - LIBTORRENT=v2
    volumes:
      - config:/config
      - Media:/Media

volumes:
  config:
    driver: local
  Media:
    driver: local